server:
  port: 8081


person:
    lastName: hsoluo
    age: 111
    boss: false
    birth: 2017/12/12
    maps: {k1:v1,k2:v2}
    lists:
     - list1
     - list2
    dog:
     name: lili
     age: 3
